# Generated by Django 4.0.2 on 2022-03-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_users_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='phone',
        ),
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='confirmpassword',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='place',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
